### ISSUE TITLE
Fix Bridge Token Allowance Process 

### ISSUE THREAD

**Issue by sukeshtedla** [telosnetwork/telos-bridge#101]
![image](https://github.com/telosnetwork/tcd-portal/assets/15923938/d708bd66-2f72-4a02-8cd6-4d8c32fd0af8)

**Comment by rozzaswap** [comment]
**Describe the bug**

To bridge USDT from ETH to TLOS, ensure you have enough USDT and ETH in your account. Approve the bridge to handle the amount of USDT you want to transfer. You can edit this amount during approval.

For example, if you set the approval amount to 1 USDT and later decide to bridge a higher amount, the bridge should prompt you for a new approval. However, it fails to do so, leading to a gas estimation error with the message "execution reverted" during the transaction.

**To Reproduce**
Try to bridge a coin, set allowance to a number less than what you want to send, then try to send.

**Expected behavior**
Bridge should always let user set allowance to the level they need to get the bridge done if the allowance is not sufficient.
